USE outfitter_db;

# TRUNCATE TABLE users;

INSERT INTO users (username, password, first_name, last_name, email, outfitter, img_user, bio, user_location)
VALUES  ('austin', '$2a$10$UJdkeUuxv/ijtvR6K0eAuehnV363r7f6HT.VZ3eHmXhhGKYhtALRK', 'Austin', 'Whitley', 'admin1@email.com', true, 'https://cdn.filestackcontent.com/X37zSRiv3Us9kRNMZALR', 'Hello there!', 'Dallas, TX'),
        ('naysa', '$2a$10$UJdkeUuxv/ijtvR6K0eAuehnV363r7f6HT.VZ3eHmXhhGKYhtALRK', 'Naysa', 'Moreno', 'admin2@email.com', true, 'https://cdn.filestackcontent.com/X37zSRiv3Us9kRNMZALR', 'Hello there!', 'San Antonio, TX'),
        ('irvin', '$2a$10$UJdkeUuxv/ijtvR6K0eAuehnV363r7f6HT.VZ3eHmXhhGKYhtALRK', 'Irvin', 'Buendia', 'admin3@email.com', true,  'https://cdn.filestackcontent.com/X37zSRiv3Us9kRNMZALR', 'Hello there!', 'San Antonio, TX'),
        ('benny', '$2a$10$UJdkeUuxv/ijtvR6K0eAuehnV363r7f6HT.VZ3eHmXhhGKYhtALRK', 'Benny', 'Alvarez', 'admin4@email.com', true,  'https://cdn.filestackcontent.com/X37zSRiv3Us9kRNMZALR', 'Hello there!', 'San Antonio, TX');

INSERT INTO properties(title, location, acres, slots, guided, lodging, method, owner_id, img_url, type)
VALUES ('West-end King ranch', 'South Texas', 100000, 125, true, true, 'rifle', 1, 'https://cdn.filestackcontent.com/Ktwfy5keSHaze3YmzsiJ', 1),
       ('Texas Exotic Hunts', 'Texas', 798, 1, true, false, 'rifle', 3, 'https://cdn.filestackcontent.com/Ktwfy5keSHaze3YmzsiJ', 1),
       ('Waterfowl package - all inclusive', 'Manitoba, Canada', 345, 1, true, false, 'shotgun', 2, 'https://cdn.filestackcontent.com/Ktwfy5keSHaze3YmzsiJ', 1),
       ('Late Season Bow Whitetail Hunt', 'British Columbia, Canada', 3763, 6, true, true, 'bow', 4, 'https://cdn.filestackcontent.com/Ktwfy5keSHaze3YmzsiJ', 1),
       ('Open Water fishing trip', 'Destin, Florida', 1, 3, true, false, 'Charter fishing', 1, 'https://cdn.filestackcontent.com/Ktwfy5keSHaze3YmzsiJ', 0);

INSERT INTO animals (id, name)
VALUES (1, 'Bear'),
       (2, 'Black Bear'),
       (3, 'Brown Bear'),
       (4, 'Grizzly Bear'),
       (5, 'Polar Bear'),
       (6, 'Bison'),
       (7, 'Wood Bison'),
       (8, 'Caribou'),
       (9, 'Barren Ground Caribou'),
       (10, 'Dolphin Caribou'),
       (11, 'Union Caribou'),
       (12, 'Woodland Caribou'),
       (13, 'Mountain Lion'),
       (14, 'Deer'),
       (15, 'Axis Deer'),
       (16, 'Black-tailed Deer'),
       (17, 'Chital'),
       (18, 'Columbian Black-tailed Deer'),
       (19, 'Mule Deer'),
       (20, 'White-tailed Deer'),
       (21, 'Elk'),
       (22, 'Rocky Mountain Elk'),
       (23, 'Tule Elk'),
       (24, 'Gemsbok'),
       (25, 'Goat'),
       (26, 'Bezoar goat'),
       (27, 'Ibex'),
       (28, 'Mountain goat'),
       (29, 'Rocky Mountain goat'),
       (30, 'Moose'),
       (31, 'Shiras Moose'),
       (32, 'Muskox'),
       (33, 'Pronghorn'),
       (34, 'Sheep'),
       (35, 'Barbary Sheep'),
       (36, 'Bighorn Sheep'),
       (37, 'California Bighorn Sheep'),
       (38, 'Dall''s Sheep'),
       (39, 'Desert Bighorn Sheep'),
       (40, 'Lanai Mouflon Sheep'),
       (41, 'Nelson Bighorn Sheep'),
       (42, 'Rocky Mountain Bighorn Sheep'),
       (43, 'Stone Sheep'),
       (44, 'Thinhorn Mountain Sheep'),
       (45, 'Armadillo'),
       (46, 'Badger'),
       (47, 'Beaver'),
       (48, 'Bobcat'),
       (49, 'North American Civet Cat'),
       (50, 'Ring-tailed Cat'),
       (51, 'Spotted Skunk'),
       (52, 'Cayote'),
       (53, 'Ferret'),
       (54, 'Feral ferret'),
       (55, 'Fisher'),
       (56, 'Fox'),
       (57, 'Arctic Fox'),
       (58, 'gray fox'),
       (59, 'red fox'),
       (60, 'swift fox'),
       (61, 'Lynx'),
       (62, 'Marmot'),
       (63, 'Alaska marmot'),
       (64, 'groundhog'),
       (65, 'hoary marmot'),
       (66, 'woodchuck'),
       (67, 'Marten'),
       (68, 'American marten'),
       (69, 'pine marten'),
       (70, 'Mink'),
       (71, 'Mole'),
       (72, 'Mouse'),
       (73, 'Muskrat'),
       (74, 'Nutria'),
       (75, 'Opossum'),
       (76, 'Pig'),
       (77, 'feral swine'),
       (78, 'javelina'),
       (79, 'wild boar'),
       (80, 'wild hogs'),
       (81, 'wild pigs'),
       (82, 'Pika'),
       (83, 'Porcupine'),
       (84, 'Prairie Dog'),
       (85, 'Black-tailed Prairie Dogs'),
       (86, 'White-tailed Prairie Dogs'),
       (87, 'Rabbit'),
       (88, 'Hare'),
       (89, 'Artic Hare'),
       (90, 'Black-tailed Jackrabbit'),
       (91, 'Cottontail Rabbit'),
       (92, 'Belgian Hare'),
       (93, 'European Hare'),
       (94, 'Snowshoe Hare'),
       (95, 'Swamp Rabbit'),
       (96, 'Varying Hare'),
       (97, 'White-tailed Jackrabbit'),
       (98, 'Raccoon'),
       (99, 'Rat'),
       (100, 'Kangaroo Rat'),
       (101, 'Wood Rat'),
       (102, 'Shrew'),
       (103, 'Skunk'),
       (104, 'Striped Skunk'),
       (105, 'Spotted Skunk'),
       (106, 'Squirrel'),
       (107, 'Abert''s Squirrel'),
       (108, 'Black Squirrel'),
       (109, 'Columbian Ground Squirrel'),
       (110, 'Gray Squirrel'),
       (111, 'Flying Squirrel'),
       (112, 'Fox Squirrel'),
       (113, 'Ground Squirrel'),
       (114, 'Pine Squirrel'),
       (115, 'Red Squirrel'),
       (116, 'Richardson''s Ground Squirrel'),
       (117, 'Tree Squirrel'),
       (118, 'Wyoming Ground Squirrel'),
       (119, 'Vole'),
       (120, 'Weasel'),
       (121, 'least weasel'),
       (122, 'long-tailed weasel'),
       (123, 'wolf'),
       (124, 'gray wolf'),
       (125, 'wolverine'),
       (126, 'Chachalaca'),
       (127, 'Chukar'),
       (128, 'Crow'),
       (129, 'Dove'),
       (130, 'Pigeon'),
       (131, 'Barred Dove'),
       (132, 'Eurasian Collared Dove'),
       (133, 'Mourning Dove'),
       (134, 'Ringed Turtledove'),
       (135, 'Rockdove'),
       (136, 'Spotted Dove'),
       (137, 'White-winged Dove'),
       (138, 'Francolin'),
       (139, 'Black Francolin'),
       (140, 'Erckel''s Francolin'),
       (141, 'Gray Francolin'),
       (142, 'Blue Grouse'),
       (143, 'Chestnut-bellied Sand Grouse'),
       (144, 'Columbian Sharp-tailed Grouse'),
       (145, 'Dusky Grouse'),
       (146, 'Forest Grouse'),
       (147, 'Franklin''s Grouse'),
       (148, 'Greater Prairie Chicken'),
       (149, 'Lesser Prairie Chicken'),
       (150, 'Ruffed Grouse'),
       (151, 'Greater Sage Grouse'),
       (152, 'Mountain Sharp-tailed Grouse'),
       (153, 'Sharp-tailed Grouse'),
       (154, 'Spruce Grouse'),
       (155, 'Partridge'),
       (156, 'Gray Partridge'),
       (157, 'Hungarian Partridge'),
       (158, 'Pheasant'),
       (159, 'Green Pheasant'),
       (160, 'Himalayan Snowcock'),
       (161, 'Kalik Pheasant'),
       (162, 'Ring-necked Pheasant'),
       (163, 'White-winged Pheasant'),
       (164, 'Ptarmigan'),
       (165, 'Rock Ptarmigan'),
       (166, 'White-tailed Ptarmigan'),
       (167, 'Willow Ptarmigan'),
       (168, 'Quail'),
       (169, 'Bobwhite'),
       (170, 'California Quail'),
       (171, 'Gambel''s Quail'),
       (172, 'Japanese Quail'),
       (173, 'Mountain Quail'),
       (174, 'Northern Bobwhite'),
       (175, 'Scaled Quail'),
       (176, 'English Sparrow'),
       (177, 'House Sparrow'),
       (178, 'Starling'),
       (179, 'Turkey'),
       (180, 'Eastern Turkey'),
       (181, 'Merriam''s Turkey'),
       (182, 'Rio Grande Turkey'),
       (183, 'Osceola Turkey'),
       (184, 'Gould''s Turkey'),
       (185, 'Cormorant'),
       (186, 'Sandhill Crane'),
       (187, 'Duck'),
       (188, 'Mallard'),
       (189, 'Black Duck'),
       (190, 'Mottled Duck'),
       (191, 'Northern Pintail'),
       (192, 'Gadwall'),
       (193, 'American Wigeon'),
       (194, 'Northern Shoveler'),
       (195, 'Blue-winged Teal'),
       (196, 'Cinnamon Teal'),
       (197, 'Green-winged Teal'),
       (198, 'Wood Duck'),
       (199, 'Fulvous Whistling-Duck'),
       (200, 'Black-bellied Whistling Duck'),
       (201, 'Redhead'),
       (202, 'Canvasback'),
       (203, 'Ring-necked Duck'),
       (204, 'Greater Scaup'),
       (205, 'Lesser Scaup'),
       (206, 'Common Goldeneye'),
       (207, 'Barrow''s Goldeneye'),
       (208, 'Bufflehead'),
       (209, 'Harlequin Duck'),
       (210, 'Common Eider'),
       (211, 'King Eider'),
       (212, 'Oldsquaw/Long-tailed Duck'),
       (213, 'Black Scoter'),
       (214, 'White-winged Scoter'),
       (215, 'Surf Scoter'),
       (216, 'Hooded Merganser'),
       (217, 'Red-breasted Merganser'),
       (218, 'Common Merganser'),
       (219, 'Ruddy Duck'),
       (220, 'Gallinule'),
       (221, 'Moorhen'),
       (222, 'American Coot'),
       (223, 'Goose'),
       (224, 'Canada Goose'),
       (225, 'Brant'),
       (226, 'Whitefronted Goose'),
       (227, 'Snow Goose'),
       (228, 'Ross'' Goose '),
       (229, 'Rail'),
       (230, 'Clapper Rail'),
       (231, 'King Rail'),
       (232, 'Sora Rail'),
       (233, 'Virginia Rail'),
       (234, 'Snipe'),
       (235, 'Wilson''s Snipe'),
       (236, 'Tundra Swan'),
       (237, 'Woodcock'),
#        ------ fish start here
        (238,'African Pompano'),
        (239,'Agujon Needlefish'),
        (240,'Alabama hog sucker'),
        (241,'Alabama sturgeon'),
        (242,'Alaska whitefish'),
        (243,'Albacore Tuna'),
        (244,'Alewife (fish)'),
        (245,'Alligator gar'),
        (246,'Ameiurus'),
        (247,'Ameiurus platycephalus'),
        (248,'American gizzard shad'),
        (249,'Anablepidae'),
        (250,'Arctic cisco'),
        (251,'Asian carp in North America'),
        (252,'Atlantic Salmon'),
        (253,'Atlantic Sharpnose Shark'),
        (254,'Banded sunfish'),
        (255,'Black Sea Bass'),
        (256,'Blue Marlin'),
        (257,'Bluefish'),
        (258,'Bluefin Tuna'),
        (259,'Choctaw bass'),
        (260,'Guadalupe bass'),
        (261,'Largemouth bass'),
        (262,'Smallmouth bass'),
        (263,'Spotted bass'),
        (264,'Beautiful shiner'),
        (265,'Bigeye shiner'),
        (266,'Bigmouth buffalo'),
        (267,'Black buffalo'),
        (268,'Black bullhead'),
        (269,'Black crappie'),
        (270,'Black madtom'),
        (271,'Black redhorse'),
        (272,'Blackbanded sunfish'),
        (273,'Blackside dace'),
        (274,'Blacktail redhorse'),
        (275,'Bleeding shiner'),
        (276,'Blue catfish'),
        (277,'Blue sucker'),
        (278,'Bluehead chub'),
        (279,'Bluespotted sunfish'),
        (280,'Bluntnose minnow'),
        (281,'Bonytail chub'),
        (282,'Brook silverside'),
        (283,'Brook stickleback'),
        (284,'Brook trout'),
        (285,'Brown trout'),
        (286,'Brown bullhead'),
        (287,'Yellow bullhead'),
        (288,'Bullhead minnow'),
        (289,'White bullhead'),
        (290,'Burbot'),
        (291,'Carmine shiner'),
        (292,'Highfin carpsucker'),
        (293,'River carpsucker'),
        (294,'Channel catfish'),
        (295,'Flathead catfish'),
        (296,'Mayan sea catfish'),
        (297,'North American freshwater catfish'),
        (298,'Central mudminnow'),
        (299,'Central stoneroller'),
        (300,'Channel darter'),
        (301,'Chiselmouth'),
        (302,'Arroyo chub'),
        (303,'Chihuahua chub'),
        (304,'Humpback chub'),
        (305,'Lake chub'),
        (306,'Coastrange sculpin'),
        (307,'Common carp'),
        (308,'Common shiner'),
        (309,'Coregonus artedi'),
        (310,'Creek chubsucker'),
        (311,'Cyprinella'),
        (312,'Cyprinella spiloptera'),
        (313,'Cyprinodon desquamatory'),
        (314,'Desert dace'),
        (315,'Eastern sand darter'),
        (316,'Diamond darter'),
        (317,'Dollar sunfish'),
        (318,'Eastern blacknose dace'),
        (319,'Eastern mudminnow'),
        (320,'Emerald shiner'),
        (321,'Exoglossum'),
        (322,'Exoglossum laurae'),
        (323,'Exoglossum maxillingua'),
        (324,'Fallfish'),
        (325,'Fantail darter'),
        (326,'Fathead minnow'),
        (327,'Finescale dace'),
        (328,'Flame chub'),
        (329,'Flier (fish)'),
        (330,'Florida gar'),
        (331,'Freshwater drum'),
        (332,'Gambusia'),
        (333,'Gila chub'),
        (334,'Golden redhorse'),
        (335,'Golden trout'),
        (336,'Goldeye'),
        (337,'Gravel chub'),
        (338,'Arctic grayling'),
        (339,'Green sunfish'),
        (340,'Greenside darter'),
        (341,'Gulf Coast pygmy sunfish'),
        (342,'Headwater chub'),
        (343,'Hiodon tergisus'),
        (344,'Hornyhead chub'),
        (345,'Ichthyomyzon unicuspis'),
        (346,'Ictaluridae'),
        (347,'Banded killifish'),
        (348,'Kokanee salmon'),
        (349,'Lake sturgeon'),
        (350,'Northern brook lamprey'),
        (351,'Silver lamprey'),
        (352,'Largescale stoneroller'),
        (353,'Laurel dace'),
        (354,'Northern studfish'),
        (355,'Northern sunfish'),
        (356,'Lavinia exilicauda'),
        (357,'Little Colorado spinedace'),
        (358,'Longnose dace'),
        (359,'Longnose gar'),
        (360,'Longnose sucker'),
        (361,'Madtom'),
        (362,'Mountain madtom'),
        (363,'Tadpole madtom'),
        (364,'Brindled madtom'),
        (365,'Micropterus henshalli'),
        (366,'Mimic shiner'),
        (367,'Moapa dace'),
        (368,'Sailfin molly'),
        (369,'Mosquitofish'),
        (370,'Mud sunfish'),
        (371,'Muskellunge'),
        (372,'Bowfin'),
        (373,'Northern hogsucker'),
        (374,'Northern leatherside chub'),
        (375,'Northern madtom'),
        (376,'Northern pearl dace'),
        (377,'Noturus flavus'),
        (378,'Noturus insignis'),
        (379,'Orangespotted sunfish'),
        (380,'Ozark bass'),
        (381,'Paddlefish'),
        (382,'Pallid sturgeon'),
        (383,'Yellow perch'),
        (384,'Percopsis omiscomaycus'),
        (385,'Chain pickerel'),
        (386,'Redfin pickerel'),
        (387,'Northern pike'),
        (388,'Poeciliidae'),
        (389,'Prietella'),
        (390,'Pumpkinseed'),
        (391,'Pygmy smelt'),
        (392,'Quillback'),
        (393,'Rainbow smelt'),
        (394,'Redbreast sunfish'),
        (395,'Redear sunfish'),
        (396,'Redfin shiner'),
        (397,'Redside dace'),
        (398,'Redspotted sunfish'),
        (399,'River chub'),
        (400,'River redhorse'),
        (401,'Roanoke hogsucker'),
        (402,'Rock bass'),
        (403,'Rosyface shiner'),
        (404,'Roundtail chub'),
        (405,'Sacramento blackfish'),
        (406,'Sacramento pikeminnow'),
        (407,'Sauger'),
        (408,'Semotilus atromaculatus'),
        (409,'Skipjack shad'),
        (410,'Shadow bass'),
        (411,'Golden shiner'),
        (412,'Red shiner'),
        (413,'Sand shiner'),
        (414,'Satinfin shiner'),
        (415,'Spottail shiner'),
        (416,'Shoal bass'),
        (417,'Shorthead redhorse'),
        (418,'Shortjaw cisco'),
        (419,'Shortnose gar'),
        (420,'Shortnose sturgeon'),
        (421,'Shovelnose sturgeon'),
        (422,'Silver redhorse'),
        (423,'Silverjaw minnow'),
        (424,'Smallmouth buffalo'),
        (425,'Southern leatherside chub'),
        (426,'Southern redbelly dace'),
        (427,'Spotted sucker'),
        (428,'Ninespine stickleback'),
        (429,'Striped shiner'),
        (430,'Texas cichlid'),
        (431,'Thoburnia rhothoeca'),
        (432,'Threadfin shad'),
        (433,'Tiger muskellunge'),
        (434,'Blackstripe topminnow'),
        (435,'Athabasca rainbow trout'),
        (436,'Cutthroat trout'),
        (437,'Kamloops rainbow trout'),
        (438,'Lake trout'),
        (439,'Rainbow trout'),
        (440,'Westslope cutthroat trout'),
        (441,'Walleye'),
        (442,'Warmouth'),
        (443,'Warpaint shiner'),
        (444,'Longear sunfish'),
        (445,'Western blacknose dace'),
        (446,'White bass'),
        (447,'White crappie'),
        (448,'White sucker'),
        (449,'Lake whitefish'),
        (450,'Mountain whitefish'),
        (451,'Pygmy whitefish'),
        (452,'Round whitefish'),
        (453,'Whitetail shiner'),
        (454,'Yaqui chub'),
        (455,'Common Dophinfish'),
        (456,'Dusky Shark'),
        (457,'Giant Seabass'),
        (458,'Goliath Grouper'),
        (459,'Great Nortern Tilefish'),
        (460,'Grey Snapper'),
        (461,'Horse-Eye Jack'),
        (462,'Houndfish'),
        (463,'King Mackerel'),
        (464,'Kingcroaker'),
        (465,'Lemon Shark'),
        (466,'Misty Grouper'),
        (467,'Mutton Snapper'),
        (468,'Nassau Grouper'),
        (469,'San Tiger Shark'),
        (470,'Sea Trout'),
        (471,'Smalltooth Sawfish'),
        (472,'Spanish Mackerel'),
        (473,'Speckled Hind'),
        (474,'Spinner Shark'),
        (475,'Spotted Weakfish'),
        (476,'Squeteague'),
        (477,'Summer Flounder'),
        (478,'Swordfish'),
        (479,'Wahoo'),
        (480,'Warsaw Grouper'),
        (481,'Yellowfin'),
        (482,'Yellowfin Tuna'),
        (483,'Other');


